# Copyright 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: '2.1'

services:
  market-processor:
    build:
      context: .
      dockerfile: ./processor/Dockerfile-installed
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: market-tp-installed
    command: ./bin/marketplace-tp -v -C tcp://validator:4004

  market-rest-api:
    build:
      context: .
      dockerfile: ./rest_api/Dockerfile-installed
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: market-rest-api-installed
    expose:
      - 8000
    ports:
      - '8040:8000'
    depends_on:
      - market-ledger-sync
      - rethink
      - validator
    command: |
      bash -c "
        sleep 1 &&
        ./bin/marketplace-rest-api \
          --host market-rest-api \
          --db-host rethink \
          --validator-host validator
      "

  market-ledger-sync:
    build:
      context: .
      dockerfile: ./ledger_sync/Dockerfile-installed
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: market-ledger-sync-installed
    depends_on:
      - rethink
      - validator
    command: |
      bash -c "
        sleep 1 &&
        bin/setup_db --host rethink
      "

  market-sawbuck-app:
    build:
      context: ./sawbuck_app
      dockerfile: ./Dockerfile-installed
    image: market-sawbuck-app-installed
    expose:
      - 80
    ports:
      - '8041:80'
    depends_on:
      - market-rest-api

  rethink:
    image: rethinkdb:2.3
    expose:
      - 28015

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    depends_on:
      - validator
    command: settings-tp -v -C tcp://validator:4004

  validator:
    image: hyperledger/sawtooth-validator:1.0
    expose:
      - 4004
    command: |
      bash -c "
        sawadm keygen &&
        sawtooth keygen my_key &&
        sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
        sawadm genesis config-genesis.batch &&
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
      "
