# Copyright 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: '2.1'

services:
  market-shell:
    build:
      context: .
      dockerfile: ./dev_env/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: market-dev-env
    container_name: market-shell
    volumes:
      - .:/project/sawtooth-marketplace
      - /project/sawtooth-marketplace/sawbuck_app/node_modules
    command: |
      bash -c "
        market-protogen &&
        cd sawbuck_app/ &&
        npm run build &&
        cd ../ &&
        tail -f /dev/null
      "

  market-processor:
    build:
      context: .
      dockerfile: ./processor/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: market-tp
    container_name: market-processor
    volumes:
      - '.:/project/sawtooth-marketplace'
    depends_on:
      - market-shell
    command: |
      bash -c "
        sleep 1 &&
        marketplace-tp -v \
          -C tcp://validator:4004
      "

  market-rest-api:
    build:
      context: .
      dockerfile: ./rest_api/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: market-rest-api
    container_name: market-rest-api
    volumes:
      - .:/project/sawtooth-marketplace
    ports:
      - '8040:8000'
    depends_on:
      - market-shell
      - market-ledger-sync
      - rethink
      - validator
    command: |
      bash -c "
        sleep 3 &&
        marketplace-rest-api \
          --host market-rest-api \
          --db-host rethink \
          --validator tcp://validator:4004
      "

  market-ledger-sync:
    build:
      context: .
      dockerfile: ./ledger_sync/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: market-ledger-sync
    container_name: market-ledger-sync
    volumes:
      - .:/project/sawtooth-marketplace
    depends_on:
      - market-shell
      - rethink
      - validator
    command: |
      bash -c "
        sleep 1 &&
        market-setup-db --host rethink &&
        marketplace-ledger-sync -vv \
          --db-host rethink \
          --validator tcp://validator:4004
      "

  market-sawbuck-app:
    build: ./sawbuck_app
    image: market-sawbuck-app
    container_name: market-sawbuck-app
    volumes:
      - ./sawbuck_app/public/:/usr/local/apache2/htdocs/
    expose:
      - 80
    ports:
      - '8041:80'
    depends_on:
      - market-shell
      - market-rest-api

  rethink:
    image: rethinkdb:2.3
    container_name: rethink-db
    expose:
      - 8080
      - 28015
    ports:
      - '8042:8080'
      - '28042:28015'

  sawtooth-rest-api:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: sawtooth-rest-api
    expose:
      - 8008
    ports:
      - '8043:8008'
    depends_on:
      - validator
    entrypoint: |
      sawtooth-rest-api -vv
        --connect tcp://validator:4004
        --bind sawtooth-rest-api:8008

  sawtooth-shell:
    image: hyperledger/sawtooth-shell:1.0
    container_name: sawtooth-shell
    volumes:
      - '.:/project/sawtooth-marketplace'
    working_dir: /project/sawtooth-marketplace
    container_name: sawtooth-shell
    depends_on:
      - sawtooth-rest-api
    entrypoint: |
      bash -c "
        if [ ! -f /root/.sawtooth/keys/root.priv ]; then
        sawtooth keygen
        fi;
        tail -f /dev/null
      "
  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: sawtooth-settings-tp
    depends_on:
      - validator
    command: settings-tp -vv --connect tcp://validator:4004

  validator:
    image: hyperledger/sawtooth-validator:1.0
    container_name: sawtooth-validator
    expose:
      - 4004
    ports:
      - '4040:4004'
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
        sawadm keygen &&
        sawtooth keygen my_key &&
        sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
        sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
      "
